### PR TITLE
Updated minimum macOS system requirements

### PR DESCRIPTION
**Pull request by ok-coder1**
Changed macOS system requirements from `macOS 10.14.5 (Mojave)` to `macOS 10.12.6 (Sierra)` based on testing.

### CODE REVIEW

**Comment by ok-coder1** [comment]
Need someone to change it on the Russian page, as I do not know Russian.

**Comment by ok-coder1** [comment]
Added an `a` to HiDPI documentation.

**Comment by ok-coder1** [comment]
Fixed typos in some documents.

**Comment by turikhay** [comment]
For typos and other unrelated things, you should open separate PRs.

**Comment by ok-coder1** [comment]
> Thanks!

Welcome!

> btw, for typos and other unrelated things, you should open separate PRs.

I could do that, but since I already had a PR already open, I figured I could save myself the hassle of creatings multiple PRs.

**Pull request merged**
